### ISSUE TITLE
Why or what is different from gridmanager.js?

### ISSUE THREAD

**Issue by Basdub** [Frontwise/grid-editor#1]
Why or what is different from gridmanager.js?

Thanks

**Comment by Epskampie** [comment]
Good question.

I wrote this because I started out using gridmanager.js, but got frustrated with the source-code.
As far as I can tell, these are the differences:

__Advantages over gridmanager.js__
* Simplified visual layout, using only rows of buttons. 
* Row adding buttons show a visual preview of the layout that will be added.
* Source code is about half shorter, and IMHO easier to read, and as such, easier to modify.
* Dragging columns to different rows works.
* Editing 'tablet' or 'phone' columns shows a preview of the page width.
* Controls are sticky at the top of the window.

__Disadvantages over gridmanager.js__
* Only extensively tested in google Chrome so far.
* Multiple "editable regions" in a column not supported. This could also be seen as an advantage, as it makes thing simpler, and most people won't need it.

**Comment by Basdub** [comment]
That sounds great! 

Can we replace the div content and update grid editor? 

Would be nice to register to events like on change, save... Don't get the saveremote as being the only saving option. 

I'll definitely take a look at your version of it.

**Comment by Epskampie** [comment]
So, did you look into it? If desired, I could add some events, but please explain more clearly the functionality you want.

**Comment by Basdub** [comment]
I did! I'm offering both options at the moment but prefer yours. Indeed your code was easier to manage and adapt. I added a save button next to the desktop button. It deinit, settings.onSave() and init. So on initialization of the grid i pass an onSave function. 

I think this is a simple and good way for user to override default behaviors of the grid-editor.

I dont know the easy way of sending you a push request. Is there an easier way to send you my mod by email?

**Comment by Basdub** [comment]
U see i wrote push request and it was pull LOL

**Comment by Epskampie** [comment]
Cool, if you want, just zip it up, upload it on https://www.wetransfer.com/ , and post the link here. I'll take a look at it.

**Comment by Epskampie** [comment]
Also, out of curiosity, can you tell me what project are you using it for?

**Comment by Basdub** [comment]
I am making a form editor/viewer. I'll be able to give you a preview soon. Optionally, the user would use it to create a template for a page or group or element layout.
here's the link
http://we.tl/Vqg7VCJSuP

**Comment by madc** [comment]
Works fine in Firefox 40.

**Comment by zotalegre** [comment]
Are there a simple way to use CKEditor instead tinyMCE? thanks

**Comment by daslicht** [comment]
Yes it is possible.

**Comment by zotalegre** [comment]
Thanks! Let me ask before I try: you didn't touch the gridmanager.js? the line 
`  'content_types' : ['tinymce']," `
stays or now you use  something like ` 'content_types': ['tinymce', 'summernote' ] `? 
thanks

**Comment by daslicht** [comment]
You are refering to this line : 
https://github.com/Frontwise/grid-editor/blob/master/src/js/jquery.grideditor.js#L58 ?
That is just the default value of the settings as far as I understand the code.

You can overwrite those default value in teh decalration of grideditor:
```
        $('#myGrid').gridEditor({
                new_row_layouts: [[12], [6,6], [9,3]],
                content_types: ['summernote'],
        });
```
